Add game interface
Blaise-Shyaka/Tic-tac-toe pull request #2
Opened 2020-09-23 21:04 UTC by Blaise-Shyaka

- Describe step by step how the game will work and how the user will interact with it﻿

2020-09-24 01:00 UTC, voscarmv requested changes
# Impressive work, team! 🖥️ 👀 ✨ 
## However, some changes are still required... 🧰 🔨 🔧 

- Please rename your file `bin/main' to 'bin/main.rb', as specified in the Pathwright instructions.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-09-24 16:59 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @Blaise-Shyaka :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, :medal_sports: your logic is good I like that you are asking for the player's names this makes your game human friendly and you are using letters instead of numbers for your game, please keep it because makes your game stand out a whole lot from the rest :video_game: :clap: please work on the following changes :construction: :construction_worker: 

##### Implementation details
> I'm sorry this wasn't pointed out by the previous reviewer but this is actually a mandatory requirement, that's why I'm sharing an example of how to do it with code, so let's add it to your code

* [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [ ] Inside the loop, you should call actions repeated for each move
* [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### That's it! :raised_hands: 

### Please :pray: do the changes :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-09-25 20:51 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ] Check comment below 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-25 20:51 UTC, kobiyoyo commented on bin/main.rb
> +    winning_move = 'e'
Can a boolean be used for the move and winning_move instead

2020-09-29 02:24 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️

- All basic requirements seem to have been met here.

### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-09-29 09:17 UTC, merged